name: MagicTorches
main: sorklin.magictorches.MagicTorches
version: 0.31
author: Sorklin
softdepend: [Multiverse]
description: MagicTorches creates linked array of wireless torches.
commands:
  mt:
    description: Information and commands regarding magictorches.
    aliases: [magictorch, magictorches]
    usage: |
           /<command> <parameter> [optional arguments]
           Type "/mt help" for more information.