name: MagicTorches
main: sorklin.magictorches.MagicTorches
version: 1.1.0
author: Sorklin
softdepend: [Multiverse, Multiverse-Core, MyWorlds, My Worlds, Vault]
description: MagicTorches creates linked array of wireless torches.
commands:
  mt:
    description: Information and commands regarding magicbuttons.
    aliases: [magictorch, magictorches]
    usage: |
           /<command> <parameter> [optional arguments]
           Type "/mt help" for more information.
permissions:
  magictorches.*:
    description: Gives all permissions for MagicTorches
    default: op
    children:
      magictorches.use:
        description: Gives full non-admin access to players
        children:
          magictorches.access:
            description: Allows player to access many MagicTorch commands, such as help
          magictorches.create.direct:
            description: Allows player to create a Direct MagicTorch Receiver
          magictorches.create.inverse:
            description: Allows player to create an Inverse MagicTorch Receiver
          magictorches.create.toggle:
            description: Allows player to create a Toggle MagicTorch Receiver
          magictorches.create.delay:
            description: Allows player to create a Delay MagicTorch Receiver
          magictorches.create.timer:
            description: Allows player to create a Timer MagicTorch Receiver
      magictorches.admin:
        description: Allows player to administrate MagicTorchs
        